# Generated by Django 5.0.7 on 2024-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userChatTelegramId', models.CharField(max_length=255, verbose_name='Id Telegram пользователя')),
                ('cost', models.CharField(max_length=255, verbose_name='Цена товара')),
                ('payId', models.CharField(max_length=255, verbose_name='Id платежа yoomoney')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payStatus', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('doneStatus', models.BooleanField(default=False, verbose_name='Статус завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userChatTelegramId', models.CharField(max_length=255, verbose_name='Id Telegram пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('firstName', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
