# Generated by Django 5.0.7 on 2024-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot_15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userChatTelegramId', models.CharField(max_length=255, verbose_name='Id Telegram пользователя')),
                ('cost', models.CharField(max_length=255, verbose_name='Цена товара')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('messages', models.JSONField(blank=True, verbose_name='Сообщения')),
                ('payStatus', models.BooleanField(default=True, null=True, verbose_name='Статус оплаты')),
                ('doneStatus', models.BooleanField(default=False, null=True, verbose_name='Статус завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
